
title: "Google Cybersecurity Certificate: My Personal Learning Journey"
description: "My blog documenting each module of the Google Cybersecurity Certificate"
author: "Jaspreet"
url: "https://jassecurity.github.io"
baseurl: "/Google-Cybersecurity-Cert"
permalink: /:title/
markdown: kramdown
highlighter: rouge
theme: just-the-docs
