title: "Google Cybersecurity Certificate: My Personal Learning Journey"
description: "My blog documenting each module of the Google Cybersecurity Certificate"
author: "Jaspreet"

remote_theme: just-the-docs/just-the-docs

url: "https://jassecurity.github.io"
baseurl: "/Google-Cybersecurity-Cert"
permalink: /:title/
markdown: kramdown
highlighter: rouge

just_the_docs:
  color_scheme: light
  search_enabled: false
